In [1]:
my_list= [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat= [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
mat = np.array(my_mat)

In [8]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [3]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.random.rand(5,5)

array([[0.80871063, 0.73526836, 0.45019193, 0.64173775, 0.8418069 ],
       [0.83864092, 0.43177653, 0.36770008, 0.90239845, 0.81300357],
       [0.21336262, 0.11829436, 0.63638107, 0.43060022, 0.66562478],
       [0.98478371, 0.20426822, 0.44903228, 0.38246083, 0.07512336],
       [0.80906434, 0.17361913, 0.77983816, 0.84329858, 0.34196489]])

In [8]:
np.random.randn(2,4)

array([[ 2.20441029, -1.11486921,  0.55463461,  1.50028983],
       [ 0.93021523, -0.39454016, -1.22920889, -0.3687904 ]])

In [10]:
np.random.randint(1,100,10)

array([39, 12,  2, 10,  6,  2, 58, 82, 81, 92])

In [12]:
arr =  np.random.randint(1,100,10)

In [13]:
arr

array([34, 94, 13, 62,  1, 67, 77, 46, 76, 59])

In [15]:
arr.reshape(5,2)

array([[34, 94],
       [13, 62],
       [ 1, 67],
       [77, 46],
       [76, 59]])

In [16]:
arr.max()

94

In [17]:
arr.min()

1

In [18]:
arr.argmax()

1

In [19]:
arr.argmin()

4

In [23]:
arr.reshape(10)

array([34, 94, 13, 62,  1, 67, 77, 46, 76, 59])

In [24]:
arr.shape()

TypeError: 'tuple' object is not callable

In [25]:
arr.dtype

dtype('int64')